# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(default='Click for more', max_length=80),
        ),
    ]
