# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20170925_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_video',
            field=models.BooleanField(default=True),
        ),
    ]
